name = "PayOff"
uuid = "9d38cedf-795c-456a-ac9a-dd77bf77f986"
authors = ["wegamekinglc <scrappedprince.li@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
